[package]
name = "builtins-test-intrinsics"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
compiler_builtins = { path = "../compiler-builtins", features = ["compiler-builtins"]}
panic-handler = { path = "../crates/panic-handler" }

[features]
c = ["compiler_builtins/c"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_family, values("solana"))',
    'cfg(target_feature, values("static-syscalls"))',
    'cfg(target_os, values("solana"))'
] }